# Generated by Django 3.1.7 on 2021-03-04 06:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myUser',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('email', models.EmailField(error_messages={'unique': 'A user with that email already exists. Try Some Other'}, help_text='Any Email', max_length=350, unique=True, verbose_name='email')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='is SuperUser')),
                ('is_staff', models.BooleanField(default=False)),
                ('is_accountant', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_analyst', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
